# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

all: pc
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=b_plus_tree_test.cpp
export BIN_OUT=b_plus_tree_test
export PC_COMPILE_DEBUG=1
export WISELIB_EXIT_MAIN=0

include ../Makefile
