# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

all: pc
# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=debug_data_alignment_problem_demo_app.cpp
export BIN_OUT=debug_data_alignment_problem_demo_app

include ../Makefile